# Tesseract configuration file for GPU deployment

name: "vlasov_sheath"
version: "0+unknown"
description: ""

build_config:
  base_image: "python:3.11-bookworm"
  target_platform: "native"
  custom_build_steps:
    - "ENV GIT_PYTHON_REFRESH=quiet"
