# Tesseract configuration file for GPU deployment

name: "vlasov_sheath"
version: "0+unknown"
description: ""

build_config:
  base_image: "nvidia/cuda:12.2.0-devel-ubuntu22.04"
  target_platform: "native"
  custom_build_steps:
    - "RUN apt-get update && apt-get install -y python3-pip python3-setuptools python3-distutils"
