# Tesseract configuration file for GPU deployment

name: "vlasov_sheath"
version: "0+unknown"
description: ""

build_config:
  base_image: "nvidia/cuda:12.2.0-devel-ubuntu22.04"
  target_platform: "native"
